/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DigitalObjectNFT__factory } from "./DigitalObjectNFT__factory";
export { ProvenanceRegistry__factory } from "./ProvenanceRegistry__factory";
export { ProvenanceRegistryV2__factory } from "./ProvenanceRegistryV2__factory";
