/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DigitalObjectNFT } from "./DigitalObjectNFT";
export type { ProvenanceRegistry } from "./ProvenanceRegistry";
export type { ProvenanceRegistryV2 } from "./ProvenanceRegistryV2";
