/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProvenanceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "KIND_LICENSE"
      | "KIND_QUALITY"
      | "KIND_REVIEW"
      | "KIND_SOURCE"
      | "attest"
      | "attestBatch"
      | "derive"
      | "deriveBatch"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Attested" | "Derived"): EventFragment;

  encodeFunctionData(
    functionFragment: "KIND_LICENSE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KIND_QUALITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KIND_REVIEW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KIND_SOURCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attest",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attestBatch",
    values: [
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "derive",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deriveBatch",
    values: [AddressLike, BigNumberish[], BigNumberish[], BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "KIND_LICENSE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KIND_QUALITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KIND_REVIEW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KIND_SOURCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "derive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deriveBatch",
    data: BytesLike
  ): Result;
}

export namespace AttestedEvent {
  export type InputTuple = [
    nft: AddressLike,
    tokenId: BigNumberish,
    attester: AddressLike,
    kind: BigNumberish,
    ref: BytesLike,
    payloadHash: BytesLike
  ];
  export type OutputTuple = [
    nft: string,
    tokenId: bigint,
    attester: string,
    kind: bigint,
    ref: string,
    payloadHash: string
  ];
  export interface OutputObject {
    nft: string;
    tokenId: bigint;
    attester: string;
    kind: bigint;
    ref: string;
    payloadHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DerivedEvent {
  export type InputTuple = [
    nft: AddressLike,
    parentId: BigNumberish,
    childId: BigNumberish,
    actor: AddressLike,
    ref: BytesLike
  ];
  export type OutputTuple = [
    nft: string,
    parentId: bigint,
    childId: bigint,
    actor: string,
    ref: string
  ];
  export interface OutputObject {
    nft: string;
    parentId: bigint;
    childId: bigint;
    actor: string;
    ref: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProvenanceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProvenanceRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProvenanceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  KIND_LICENSE: TypedContractMethod<[], [bigint], "view">;

  KIND_QUALITY: TypedContractMethod<[], [bigint], "view">;

  KIND_REVIEW: TypedContractMethod<[], [bigint], "view">;

  KIND_SOURCE: TypedContractMethod<[], [bigint], "view">;

  attest: TypedContractMethod<
    [
      nft: AddressLike,
      tokenId: BigNumberish,
      kind: BigNumberish,
      ref: BytesLike,
      payloadHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  attestBatch: TypedContractMethod<
    [
      nft: AddressLike,
      tokenIds: BigNumberish[],
      kinds: BigNumberish[],
      refs: BytesLike[],
      payloadHashes: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  derive: TypedContractMethod<
    [
      nft: AddressLike,
      parentId: BigNumberish,
      childId: BigNumberish,
      ref: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  deriveBatch: TypedContractMethod<
    [
      nft: AddressLike,
      parentIds: BigNumberish[],
      childIds: BigNumberish[],
      refs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "KIND_LICENSE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KIND_QUALITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KIND_REVIEW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KIND_SOURCE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [
      nft: AddressLike,
      tokenId: BigNumberish,
      kind: BigNumberish,
      ref: BytesLike,
      payloadHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attestBatch"
  ): TypedContractMethod<
    [
      nft: AddressLike,
      tokenIds: BigNumberish[],
      kinds: BigNumberish[],
      refs: BytesLike[],
      payloadHashes: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "derive"
  ): TypedContractMethod<
    [
      nft: AddressLike,
      parentId: BigNumberish,
      childId: BigNumberish,
      ref: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deriveBatch"
  ): TypedContractMethod<
    [
      nft: AddressLike,
      parentIds: BigNumberish[],
      childIds: BigNumberish[],
      refs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Attested"
  ): TypedContractEvent<
    AttestedEvent.InputTuple,
    AttestedEvent.OutputTuple,
    AttestedEvent.OutputObject
  >;
  getEvent(
    key: "Derived"
  ): TypedContractEvent<
    DerivedEvent.InputTuple,
    DerivedEvent.OutputTuple,
    DerivedEvent.OutputObject
  >;

  filters: {
    "Attested(address,uint256,address,uint8,bytes32,bytes32)": TypedContractEvent<
      AttestedEvent.InputTuple,
      AttestedEvent.OutputTuple,
      AttestedEvent.OutputObject
    >;
    Attested: TypedContractEvent<
      AttestedEvent.InputTuple,
      AttestedEvent.OutputTuple,
      AttestedEvent.OutputObject
    >;

    "Derived(address,uint256,uint256,address,bytes32)": TypedContractEvent<
      DerivedEvent.InputTuple,
      DerivedEvent.OutputTuple,
      DerivedEvent.OutputObject
    >;
    Derived: TypedContractEvent<
      DerivedEvent.InputTuple,
      DerivedEvent.OutputTuple,
      DerivedEvent.OutputObject
    >;
  };
}
